collections:
  staff:
    output: false
  clients:
    output: true

paginate: 10
paginate_path: "/blog/:num/"
permalink: pretty

jekyll-archives:
  enabled: ['categories']

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "clients"
    values:
      layout: "client"
  -
    scope:
      path: "pages"
      type: "pages"
    values:
      layout: "page"


